### ISSUE TITLE
installation fails if system-wide libspdlog is available

### ISSUE THREAD

**Issue by mdimura** [yesint/pteros#2]
```
> make install
...
trying to overwrite '/usr/include/spdlog/async_logger.h', which is also in package libspdlog-dev 1.6-1
```

**Comment by yesint** [comment]
Yes, this is a problem.
For now we can provide a flag to disable internal spdlog to be installed but I don't like this.

**Comment by mdimura** [comment]
Could we provide our own spdlogConfig.cmake so that it [works](https://github.com/gabime/spdlog/wiki/9.-CMake#install) anyway?

**Comment by yesint** [comment]
Ok, I got it. The real problem is that libspdlog-dev package in Ubuntu is incomplete and lacks CMake package detection files. If one installs it with `make;make install` everything is Ok. That is why detecting system-wide spdlog become tricky. 
For now:
- If spdlog is installed system-wide from command line then spdlogConfig.cmake is in place Pteros will just detect and use it.
- If  spdlog is installed from package AND you want to install Pteros system-wide you have to specify `INSTALL_INTERNAL_SPDLOG=OFF` because otherwise you'll get an overwrite conflict.
- If no spdlog is installed system-wide Pteros installs it's internal spdlog with no problem.
