### ISSUE TITLE
Reading topology information.

### ISSUE THREAD

**Issue by rkalescky** [yesint/pteros#24]
Thank you for your useful library. 👍 What is best way to read in topology information such that `get_internal_bonds` can be used? I've been reading in PDB and MOL2 files, both with bonding information. At the moment, I'm just interested in a single set of coordinates, i.e. single frame.

**Comment by yesint** [comment]
Currently the topology itself (in the meaning of MD simulations) is only read from the Gromacs TPR files. However, in order to use `get_internal_bonds` you don't need this. Just read in your file and use `get_internal_bonds` with the first parameter d>0. In this case it will find all atoms within the distance d apart and treat them as connected by the bonds.

**Comment by rkalescky** [comment]
Right, thank you. I was hoping to avoid specifying d and just use the bonding information directly.

**Comment by yesint** [comment]
The reason for this is that Pteros treats "topology" in the same sense as MD engines do, i.e. not only as bonds, but also exclusions, molecules and some force field parameters. This is unlike from what is use in VMD and some other programs and libraries. Reading bonds from file formats which support them is in the TODO list, however. If you want to contribute to this - you are welcome.

**Comment by rkalescky** [comment]
I completely understand. Just curious if there were, perhaps, workarounds that others were using.
