### ISSUE TITLE
Gromacs API Update Causing Issues

### ISSUE THREAD

**Issue by Cweb118** [yesint/pteros#27]
Hello!

I am attempting to install Pteros and I have run into an issue that seems to stem from an update gromacs did to their API about a month ago. Below is the error from the terminal:

```
Consolidate compiler generated dependencies of target dssp
Consolidate compiler generated dependencies of target pteros_io
[ 43%] Built target dssp
[ 44%] Building CXX object src/core/io/CMakeFiles/pteros_io.dir/tpr_file.cpp.o
In file included from /home/user/Desktop/pteros-master/build/temp.linux-x86_64-3.9/_deps/gromacs_external_fetch-src/api/legacy/include/gromacs/fileio/tpxio.h:42,
                 from /home/user/Desktop/pteros-master/src/core/io/tpr_file.cpp:34:
/home/user/Desktop/pteros-master/build/temp.linux-x86_64-3.9/_deps/gromacs_external_fetch-src/api/legacy/include/gromacs/pbcutil/pbc.h:41:10: fatal error: gromacs/libgromacs_export.h: No such file or directory
 #include "gromacs/libgromacs_export.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/core/io/CMakeFiles/pteros_io.dir/build.make:258: src/core/io/CMakeFiles/pteros_io.dir/tpr_file.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1177: src/core/io/CMakeFiles/pteros_io.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
error: command '/home/user/anaconda3/bin/cmake' failed with exit code 2
```

This seems to be stemming from #include "gromacs/libgromacs_export.h", as it would seem this no longer exists with the new API version. This does not seem to be the only missing file unfortunately, as #include #include "gromacs/utility/alignedallocator.h" caused the same issue in pbcutil/pbc.h

Does there happen to be a way to instruct the installation process to use the older version of gromacs?

**Comment by yesint** [comment]
There is a major pain with Gromacs API because Pteros have to use many internal headers, which are not exposed by public API. They are changing all the time, causing such issues.

I'll try to fix it, but for now please use older Gromacs version. There are two ways of doing this:
1) In cmake/gromacs.cmake change GIT_TAG from "main" to any of the older versions.
2) Install any desired version of Gromacs manually and use -DTRY_SYSTEM_GROMACS=ON -DGROMACS_SOURCE_DIR="..." -DGROMACS_BINARY_DIR="..." to point to installed version.

**Comment by yesint** [comment]
Fixed in the latest commit.
