### ISSUE TITLE
Build fails when -DWITH_OPENBABEL=OFF is specified

### ISSUE THREAD

**Issue by mdimura** [yesint/pteros#9]
If cmake is configured like this:
```
x86_64-w64-mingw32-cmake -DWITH_PYTHON=OFF -DWITH_OPENBABEL=OFF ..
```

The `make` fails with:

> In file included from /home/devel/pteros/src/core/io/pdbqt_file.h:30,
> from /home/devel/pteros/src/core/io/mol_file.cpp:38:
> /home/devel/pteros/src/core/io/babel_wrapper.h:35:10: fatal error: openbabel/obconversion.h: No such file or directory
>  #include <openbabel/obconversion.h>

**Comment by yesint** [comment]
Fixed. Please try if it works.

**Comment by mdimura** [comment]
Now I get another error:

> In file included from /home/devel/pteros/src/core/io/gromacs_trajectory_file.cpp:32:
> /home/devel/pteros/include/pteros/core/logging.h: At global scope:
> /home/devel/pteros/include/pteros/core/logging.h:49:34: error: 'stdout_sink_st' is not a member of 'spdlog::sinks'
>    std::shared_ptr<spdlog::sinks::stdout_sink_st> console_sink;

Here is the way to reproduce it. Start a container: `sudo docker run -it burningdaylight/docker-mingw-qt5 /bin/bash`
and then inside the container:
```
git clone https://github.com/yesint/pteros.git pteros;
cd pteros; rm -rf build; mkdir build; cd build
x86_64-w64-mingw32-cmake -DWITH_PYTHON=OFF -DWITH_OPENBABEL=OFF ..
make
```

**Comment by yesint** [comment]
This is not our bug. This seems to be a bug in mingw compiler. stdout_sink_st is defined correctly (this is not our code but a part of spdlog). 

cmake -DWITH_PYTHON=OFF -DWITH_OPENBABEL=OFF ..
compiles with no problems in Linux with both gcc-7.3 and clang-6.0.

Could you try compiling with clang in your mingw environment to see if it works? 
It is too tedious for me to mess with docker, so please be responsible for mingw yourself since you use it anyway :)
